{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha05.aar",
          "url": "navigation-runtime-2.4.0-alpha05.aar",
          "size": 112694,
          "sha512": "f8fa165312620b3011a361527bf44bcd214c7a8c32587767fb500bf595ef40f93720b90d8f18133d38e9682523be96546437640587fef45ce5686701c0812749",
          "sha256": "8970fc8437a26fbc470907ee364b5266a983c13ce647efab903a910beb1f0478",
          "sha1": "16cf44b6d0a1c575f65702240799e739ac5346e4",
          "md5": "2749ab7f5fd40dadd4a584816a99fecd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha05.aar",
          "url": "navigation-runtime-2.4.0-alpha05.aar",
          "size": 112694,
          "sha512": "f8fa165312620b3011a361527bf44bcd214c7a8c32587767fb500bf595ef40f93720b90d8f18133d38e9682523be96546437640587fef45ce5686701c0812749",
          "sha256": "8970fc8437a26fbc470907ee364b5266a983c13ce647efab903a910beb1f0478",
          "sha1": "16cf44b6d0a1c575f65702240799e739ac5346e4",
          "md5": "2749ab7f5fd40dadd4a584816a99fecd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha05-sources.jar",
          "url": "navigation-runtime-2.4.0-alpha05-sources.jar",
          "size": 43171,
          "sha512": "ff519181cfecb56688057f80760cb8ee5985fcb95f0b7fd43877c805fff68ed80d6aa2b197d64d3e521ffc152544d80ac5a4fc3849d7fe72e8056761b451a53e",
          "sha256": "76664001eea146b4fe25d5edd186f03034ed1cbeb1e9d33cda05908b3d091077",
          "sha1": "6ab25ec6aec28d94efc41cf1786b186b1cecdc3a",
          "md5": "601d613ae041303d94354823f1367504"
        }
      ]
    }
  ]
}
