{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0-rc02"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.0-alpha05.aar",
          "url": "navigation-compose-2.4.0-alpha05.aar",
          "size": 63448,
          "sha512": "80095a2fb34d45da902da9c480dbd8ae06c1d57965e10c89b418b5cf58c8548694b3ac14a18b80a669de83578499b6e379b4bcf171ebcb2ebc71f016a30225c7",
          "sha256": "4a0c95cb1bc9984f31dcdca935905f4b96c386d2362e3430288cde981f941db6",
          "sha1": "e240150885a87d1d952430ccc3dc0dbcc39057dd",
          "md5": "95da5a915f1803de9511d5495fdf67ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0-rc02"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.0-alpha05.aar",
          "url": "navigation-compose-2.4.0-alpha05.aar",
          "size": 63448,
          "sha512": "80095a2fb34d45da902da9c480dbd8ae06c1d57965e10c89b418b5cf58c8548694b3ac14a18b80a669de83578499b6e379b4bcf171ebcb2ebc71f016a30225c7",
          "sha256": "4a0c95cb1bc9984f31dcdca935905f4b96c386d2362e3430288cde981f941db6",
          "sha1": "e240150885a87d1d952430ccc3dc0dbcc39057dd",
          "md5": "95da5a915f1803de9511d5495fdf67ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.4.0-alpha05-sources.jar",
          "url": "navigation-compose-2.4.0-alpha05-sources.jar",
          "size": 11558,
          "sha512": "0eceab4318ed759b6a6ac4322edc9ece8577d6b890393bc4d82511f55f227590770095f98ba08f3c47357c008d733f7097c195d74e22971b0bebd72ad2b8b87d",
          "sha256": "9583347f509f4e647b69ff4bee7041472af3f997382d5ef2a3b3b0183a8dac34",
          "sha1": "00d23915fd53084e49eb5485b1a6ea79e2fc29de",
          "md5": "0d8591909a32791b703e3fc0f394317c"
        }
      ]
    }
  ]
}
