{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-dynamic-features-runtime",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.3.5.aar",
          "url": "navigation-dynamic-features-runtime-2.3.5.aar",
          "size": 45491,
          "sha512": "719e9602cd6a7a8ff59cea67493c407bcd0ab9a294b8cb37b48d4b925f738ad539237aeecda341bdf2c2a5853092e1d2a111196d48f143ef9956da63797c781c",
          "sha256": "28e4ce8249d39b48f5114714db530c5f1dbe10e368630025ed4d2d957d146341",
          "sha1": "12f64c3d92251032bb97165cd481ef6f62b41980",
          "md5": "1cf489e3d88194b741b7f943390660ae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.3.5.aar",
          "url": "navigation-dynamic-features-runtime-2.3.5.aar",
          "size": 45491,
          "sha512": "719e9602cd6a7a8ff59cea67493c407bcd0ab9a294b8cb37b48d4b925f738ad539237aeecda341bdf2c2a5853092e1d2a111196d48f143ef9956da63797c781c",
          "sha256": "28e4ce8249d39b48f5114714db530c5f1dbe10e368630025ed4d2d957d146341",
          "sha1": "12f64c3d92251032bb97165cd481ef6f62b41980",
          "md5": "1cf489e3d88194b741b7f943390660ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.3.5-sources.jar",
          "url": "navigation-dynamic-features-runtime-2.3.5-sources.jar",
          "size": 18099,
          "sha512": "c734e86cedc36814250a11db4ffc89c2f19ae03c5a311fb3ed8af4c1e280e00fc281e99f90ff0eef8f97267af9ee7e72f5a3496bf53dd20da9493f2ccc7d4b01",
          "sha256": "b20eca822485c97202c1398cf22d5393dd8bd4236dc02f7ef322ee836317d38d",
          "sha1": "800851d92f601cd3949e421409554dfd6b05aa89",
          "md5": "bf35acf00401c1f24504dc80a50377db"
        }
      ]
    }
  ]
}
