{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.4.0-alpha05.aar",
          "url": "navigation-common-2.4.0-alpha05.aar",
          "size": 150943,
          "sha512": "e7d5dd0b76d57e5cfd9f8fecb02cff22d0368737b72c5093a622340962f68310c325ad93a553b0085e303f34ce2b54d18058fce246753e6c29b56596af2c0669",
          "sha256": "f42b096a89d275eb530250dc63098c34507e454d805829c77467fdc653fe26c4",
          "sha1": "3ce985c9747bcc81545525bd704319658e4ce480",
          "md5": "742259b25dc97b0756642a655c0fd0d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.4.0-alpha05.aar",
          "url": "navigation-common-2.4.0-alpha05.aar",
          "size": 150943,
          "sha512": "e7d5dd0b76d57e5cfd9f8fecb02cff22d0368737b72c5093a622340962f68310c325ad93a553b0085e303f34ce2b54d18058fce246753e6c29b56596af2c0669",
          "sha256": "f42b096a89d275eb530250dc63098c34507e454d805829c77467fdc653fe26c4",
          "sha1": "3ce985c9747bcc81545525bd704319658e4ce480",
          "md5": "742259b25dc97b0756642a655c0fd0d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.4.0-alpha05-sources.jar",
          "url": "navigation-common-2.4.0-alpha05-sources.jar",
          "size": 52310,
          "sha512": "2c6539285875044090481136ea5ae8dabb6febdd08d8ffdfab4347d7efc4eb7ab13149ec31bf5343a070e57bf25026d4579cbc0bc2846421c8b798eb303974f0",
          "sha256": "5ad805791041c63a8b1b417eeedd2b410ca945f17dc6543310bfb71f84d41636",
          "sha1": "b315e9feb9ebcc2851b27aa960f539eb8902fde9",
          "md5": "732fc65cec2c5ff370e095c05c09beaa"
        }
      ]
    }
  ]
}
