{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha05"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha05.aar",
          "url": "navigation-runtime-ktx-2.4.0-alpha05.aar",
          "size": 1754,
          "sha512": "4eee2f41c19340f8f0a2135938f16a68cec3a06b64d526557cc21bbfd4c33452247dada1088b126eb95dde6a7a116d7a10c42c9685afa8f3579ba73bf53486d9",
          "sha256": "92fb9a1660452e7ea9558d336b14c5d122530718abe2ef622e04019243ee888a",
          "sha1": "9ed736b3d845d86402514a8cd74109557e85dff6",
          "md5": "76fd55b1049dff384834084483bad03c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha05"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha05.aar",
          "url": "navigation-runtime-ktx-2.4.0-alpha05.aar",
          "size": 1754,
          "sha512": "4eee2f41c19340f8f0a2135938f16a68cec3a06b64d526557cc21bbfd4c33452247dada1088b126eb95dde6a7a116d7a10c42c9685afa8f3579ba73bf53486d9",
          "sha256": "92fb9a1660452e7ea9558d336b14c5d122530718abe2ef622e04019243ee888a",
          "sha1": "9ed736b3d845d86402514a8cd74109557e85dff6",
          "md5": "76fd55b1049dff384834084483bad03c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha05-sources.jar",
          "url": "navigation-runtime-ktx-2.4.0-alpha05-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
