{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-dynamic-features-fragment",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.3.5.aar",
          "url": "navigation-dynamic-features-fragment-2.3.5.aar",
          "size": 92355,
          "sha512": "9834f47a53084ff966ce1bd07a69dec5eafe8302e2521f6ecc2a78f876416770fee7006e93ba8c84ec78c6c00df0bf9ad57bba6e5cf26167f710fc2a1fea9925",
          "sha256": "9b6f8e5d5cf060284d7d6644596766ea3d536d4171975d011037d1330b1f0bdc",
          "sha1": "bd4506a5fcc810d1ebc5ada728332c5792e2ad74",
          "md5": "dd0550032aaee8d5ca55161c0de36104"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.3.5.aar",
          "url": "navigation-dynamic-features-fragment-2.3.5.aar",
          "size": 92355,
          "sha512": "9834f47a53084ff966ce1bd07a69dec5eafe8302e2521f6ecc2a78f876416770fee7006e93ba8c84ec78c6c00df0bf9ad57bba6e5cf26167f710fc2a1fea9925",
          "sha256": "9b6f8e5d5cf060284d7d6644596766ea3d536d4171975d011037d1330b1f0bdc",
          "sha1": "bd4506a5fcc810d1ebc5ada728332c5792e2ad74",
          "md5": "dd0550032aaee8d5ca55161c0de36104"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.3.5-sources.jar",
          "url": "navigation-dynamic-features-fragment-2.3.5-sources.jar",
          "size": 9808,
          "sha512": "8057d5e156a3c41e406794a2204105cf189daa8a746a80fcbd24bb0e7f7a3664b9e181025a4fe40a3921191eaa6f2fc337ab370f0c1aa3bbe41d6e0a7867ddc5",
          "sha256": "eee9ecb790ea2f0af2164a28691d801255900a0586d5b49dde3bef53f2fe8beb",
          "sha1": "c5245099185735bd6ba7998f5dda5a27b38dd4e0",
          "md5": "f6d26e22efd4a0bfba1f4e4b1ae7df6f"
        }
      ]
    }
  ]
}
