{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-testing",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.3.5.aar",
          "url": "navigation-testing-2.3.5.aar",
          "size": 6811,
          "sha512": "abbf33570c561092cc0927896ca19b54101b1f0648c41ea0a8d35b1dd6480a4b061fa393ccf94c37d5d7f95f525f60e5ac7684a3116c3934c1a685acf1f383e7",
          "sha256": "590050bc7202c241bc254466c04cfd811c398d162e67c75ec7ff3a409a2b7ad6",
          "sha1": "ff0a9c3b58001046f70392faeab9a3f94f92e4b1",
          "md5": "a5933b1c9eeefe818fcbc62257a38e5b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.3.5.aar",
          "url": "navigation-testing-2.3.5.aar",
          "size": 6811,
          "sha512": "abbf33570c561092cc0927896ca19b54101b1f0648c41ea0a8d35b1dd6480a4b061fa393ccf94c37d5d7f95f525f60e5ac7684a3116c3934c1a685acf1f383e7",
          "sha256": "590050bc7202c241bc254466c04cfd811c398d162e67c75ec7ff3a409a2b7ad6",
          "sha1": "ff0a9c3b58001046f70392faeab9a3f94f92e4b1",
          "md5": "a5933b1c9eeefe818fcbc62257a38e5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-testing-2.3.5-sources.jar",
          "url": "navigation-testing-2.3.5-sources.jar",
          "size": 2787,
          "sha512": "d4fdad036039c2d8fbdbd7b6e9c32152f051706ae6e9693ad0972d1e76bcc8c1ab9fd13f91af8760a138464bf970a6162142bf2781ab61e288b70aae29ea12a6",
          "sha256": "4ec6c20a14734638cef462b19781ee4e8b8ef92163f748300e53b037f0af778f",
          "sha1": "a29af714846d56357a9a2905d96686d212d69d0d",
          "md5": "2e981364c67ebbf440e713ffa31c21b8"
        }
      ]
    }
  ]
}
