{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha05.aar",
          "url": "navigation-common-ktx-2.4.0-alpha05.aar",
          "size": 1754,
          "sha512": "aa835db051138a9d9fcfc375e6d2f1a4e906ee8a6e1c19d90f3daf43ca65b4be7cf3ae4448a42413748218a385ed14c5836b2dbab6df19a83dedc1014ad19017",
          "sha256": "9a14e71f349d17889f86270698b0f404dffa532c63fc23f4a69eb523eae9ca39",
          "sha1": "fb1150790b9d77351f8954ef2673f2167a8139f2",
          "md5": "2c61ecb83c141a877092ae96dc638a2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha05.aar",
          "url": "navigation-common-ktx-2.4.0-alpha05.aar",
          "size": 1754,
          "sha512": "aa835db051138a9d9fcfc375e6d2f1a4e906ee8a6e1c19d90f3daf43ca65b4be7cf3ae4448a42413748218a385ed14c5836b2dbab6df19a83dedc1014ad19017",
          "sha256": "9a14e71f349d17889f86270698b0f404dffa532c63fc23f4a69eb523eae9ca39",
          "sha1": "fb1150790b9d77351f8954ef2673f2167a8139f2",
          "md5": "2c61ecb83c141a877092ae96dc638a2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha05-sources.jar",
          "url": "navigation-common-ktx-2.4.0-alpha05-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
